<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
   <head>
     <meta  charset=utf-8" />
     <?php echo $this->headTitle('Online Shop')?>
     <?php echo $this->headMeta()
                ->appendName('viewport','width=device-width, initila-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible','IE=edge')
     ?>
      <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/shop/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
             ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath().'/js/bootstrap.min.js')
            ->appendFile($this->basePath().'/js/jquery.min.js')
            ->appendFile($this->basePath().'/js/shop/jqueryui-widget.min.js') 
            ->appendFile($this->basePath().'/js/shop/simple-gallery.min.js')
            ->appendFile($this->basePath().'/js/shop/jquery-1.4.1.min.js')
            ->appendFile($this->basePath().'/js/shop/jquery-func.js')
            ->appendFile($this->basePath().'/js/shop/jquery.jcarousel.pack.js')
            ->appendFile($this->basePath().'/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath().'/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))

        ; ?>
</head>
<body>
     <?php echo $this->content; ?>   
    
</body>
<script>
        $('#full').gallery({
            source: "#images img",
            easing: "linear",
            waitTime: 20000,
            changeTime: 200,
            showCaptions: true,
            captionTarget: "#caption"
        });
        
        $("#full").on({
            mouseenter: function() {
                $("#full").gallery("stopAnimation");
            },
            mouseleave: function() {
                $("#full").gallery("resumeAnimation");
            }
        });
</script>   
</html>

