<!-- Shell -->
<div class="shell">
  <!-- Header -->
  <div id="header">
    <h1 id="logo"><a href="#">shoparound</a></h1>
    <!-- Cart -->
    <div id="cart"> <a href="<?php echo $this->url('shoppingcart',array('action'=>'show'));?>" class="cart-link">Your Shopping Cart</a>
      <div class="cl">&nbsp;</div>
      <span>Items: <strong><?php if (isset($_SESSION['cart'])){echo $shoppingcart->getNumberOfItems();} else {echo "0";}?></strong></span> &nbsp;&nbsp;<span>Cost: <strong><?php if (isset($_SESSION['cart'])){echo $shoppingcart->calculateTotals();} else {echo "0.0";}?></strong></span> </div>
    <!-- End Cart -->
    <!-- Navigation -->
    <div id="navigation">
      <ul>
        <li><a href="<?php echo $this->url('home',array('action'=>'index'));?>">Home</a></li>
        <li><a href="<?php echo $this->url('home',array('action'=>'support'));?>">Support</a></li>
        <li><a href="<?php echo $this->url('home',array('action'=>'myaccount'));?>">My Account</a></li>
        <li><a href="<?php echo $this->url('home',array('action'=>'thestore'));?>">The Store</a></li>
        <li><a href="<?php echo $this->url('home',array('action'=>'contact'));?>">Contact</a></li>
      </ul>
    </div>
    <!-- End Navigation -->
  </div>
  <!-- End Header -->
  <!-- Main -->
  <div id="main">
    <div class="cl">&nbsp;</div>
    <!-- Content -->
    <div id="content">
      <!-- Products -->
        <div class="single-product">
              <div class="cl">&nbsp;</div>
              <div id="images">
                  <div class="row">
                    <img src="<?php echo $product->photo1_url;?>" title="">
                  </div> 
                  <div class="row">
                    <img src="<?php echo $product->photo2_url;?>" title="">
                  </div>  
                  <div class="row">
                    <img src="<?php echo $product->photo3_url;?>" title="">
                  </div>  
                  <div class="row">
                    <img src="<?php echo $product->photo4_url;?>" title="">
                  </div>  
              </div>
              <div id="full"></div>
              <p id="caption"></p>         
              <div class="product-name"><h3><?php echo $product->product_name;?></h3></div>
              <div class="product-desc1"><h4><?php echo $product->description1;?></h4></div>
              <div class="product-desc2"><p><?php echo $product->description2;?></p></div>
              <strong class="price">$<?php echo $product->price;?></strong> </div>
              <div class="product-size"><?php echo $product->size;?></div>
              <div class="product-colors"><?php echo $product->colors;?></div> 
              <div> <a href="<?php echo $this->url('shoppingcart',array('action'=>'addToCart', 'id'=>$product->id )); ?>">add to cart </a></div>
              <div class="cl">&nbsp;</div>
      </div>
      <!-- End Products -->
    </div>
    <!-- End Content -->
    <!-- Sidebar -->
    <div id="sidebar">
      <!-- Search -->
      <div class="box search">
        <h2>Search by <span></span></h2>
<?php
echo "<div class='inline-field'>";
$form->setAttribute('action', $this->url('home', array('action' => 'search')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('category'))."<br/>";
echo $this->formRow($form->get('startprice'));echo $this->formRow($form->get('endprice'));
echo "</div>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
    </div>
      <!-- End Search -->
      <!-- Categories -->
      <div class="box categories">
        <h2>Categories <span></span></h2>
        <div class="box-content">
          <ul>
             <?php $len = count($categories);$counter=1; ?>
             <?php foreach($categories as $category):?>
              <li<?php if($counter==$len) echo " class=\"last\"";?>><a href="<?php echo $this->url('categorypage',array('action'=>'index')); ?>"><?php echo $category->category_display;?></a></li>
            <?php $counter++;?>
            <?php endforeach; ?>
          </ul>
        </div>
      </div>
      <!-- End Categories -->
    </div>
    <!-- End Sidebar -->
    <div class="cl">&nbsp;</div>
  </div>
  <!-- End Main -->
  <!-- Side Full -->
  <div class="side-full">

  </div>
  <!-- End Side Full -->
  <!-- Footer -->
  <div id="footer">
    <p class="left"> <a href="<?php echo $this->url('home',array('action'=>'index'));?>">Home</a> <span>|</span> <a href="<?php echo $this->url('home',array('action'=>'support'));?>">Support</a> <span>|</span> <a href="<?php echo $this->url('home',array('action'=>'myaccount'));?>">My Account</a> <span>|</span> <a href="<?php echo $this->url('home',array('action'=>'thestore'));?>">The Store</a> <span>|</span> <a href="<?php echo $this->url('home',array('action'=>'contact'));?>">Contact</a> </p>
    <p class="right"> &copy; 2010 Shop Around. Design by <a href="http://chocotemplates.com">Chocotemplates.com</a> </p>
  </div>
  <!-- End Footer -->
</div>
<!-- End Shell -->
