<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
   <head>
     <meta  charset=utf-8" />
     <?php echo $this->headTitle('Online Shop')?>
     <?php echo $this->headMeta()
                ->appendName('viewport','width=device-width, initila-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible','IE=edge')
     ?>
      <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/shop/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
             ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath().'/js/bootstrap.min.js')
            ->prependFile($this->basePath().'/js/jquery.min.js')
            ->prependFile($this->basePath().'/js/shop/jquery-func.js')
            ->prependFile($this->basePath().'/js/shop/jquery.jcarousel.pach.js')
            ->prependFile($this->basePath().'/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath().'/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
</head>
<body>
     <?php echo $this->content; ?>     
</body>
</html>
