<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Shop Around</title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="/css/shop/style.css" type="text/css" media="all" />
<!--[if lte IE 6]><link rel="stylesheet" href="css/ie6.css" type="text/css" media="all" /><![endif]-->
<script src="/js/shop/jquery-1.4.1.min.js" type="text/javascript"></script>
<script src="/js/shop/jquery.jcarousel.pack.js" type="text/javascript"></script>
<script src="/js/shop/jquery-func.js" type="text/javascript"></script>
<script src="/js/shop/image.js>" type="text/javascript"></script>
<script src="/js/shop/imagemain.js>" type="text/javascript"></script>
</head>
<body>

<?php echo $this->content; ?>     
</body>
</html>
