<?php
$title = 'Edit Category Page';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('categorypage', 
                      array(
                            'action' => 'edit',
                            'id'     => $this->id,
                             )
                       ));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('category'))."<br />";
echo $this->formRow($form->get('category_display'))."<br />";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
