<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta  charset="utf-8" />
<?php echo $this->headMeta()
->appendName('viewport','width=device-width, initila-scale=1.0')
->appendHttpEquiv('X-UA-Compatible','IE=edge')
?>
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))->prependStylesheet($this->basePath() . '/css/shop/style.css'); ?>
<!-- Scripts -->
<?php echo $this->headScript()
->prependFile($this->basePath().'/js/jquery.min.js', 'text/javascript')
->prependFile($this->basePath().'/js/shop/jquery-func.js', 'text/javascript')
->prependFile($this->basePath().'/js/shop/jquery.jcarousel.pach.js', 'text/javascript')
->prependFile($this->basePath().'/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
->prependFile($this->basePath().'/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9'));?>
</head>
<body>
<?php echo $this->content; ?>     
</body>
</html>
